version: '3.8'
name: opportunity_spring
services:
  pgdb:
    image: "postgres:latest"
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
volumes:
  pgdata:
    driver: local